package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/bxcodec/go-clean-arch/models"

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: articleID
func (_m *CategoryRepository) Fetch(articleID int64) ([]*models.Category, error) {
	ret := _m.Called(articleID)

	var r0 []*models.Category
	if rf, ok := ret.Get(0).(func(int64) []*models.Category); ok {
		r0 = rf(articleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(articleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
